
OBJS=mod_pubcookie.o libpubcookie.o base64.o

libpubcookie.a:	$(OBJS)

.c.o:
	$(CC) -c $(INCLUDES) $(CFLAGS) -DAPACHE1_3 $(SSL_CFLAGS) $<

#Dependencies

$(OBJS): Makefile

# DO NOT REMOVE
# DO NOT DELETE THIS LINE -- make depend depends on it.
libpubcookie.o: libpubcookie.c libpubcookie.h pubcookie.h pbc_config.h pbc_version.h

